import Link from "next/link";
import { Card, Button } from "antd";
import Head from "next/head";

const key = process.env.NEXT_PUBLIC_NEWS_API_KEY;
export const getStaticProps = async () => {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?country=id&category=business&apiKey=${key}`
  );
  const data = await res.json();
  const { articles } = data;

  return {
    props: { datas: articles },
  };
};

const Home = ({ datas }: { datas: any }) => {
  return (
    <>
      <Head>
        <title>Test FrontEnd || PT. Eigen </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;800&family=Montserrat:wght@100;200;300;500;700&family=Quicksand:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="text-red-800 font-montserrat pt-14 pb-2 text-center font-bold text-4xl  ">
        PORTAL BERITA
      </div>
      <p className="pb-5 font-montserrat text-center font-light text-xs">
        Frontend || Tony Aji Palguno
      </p>
      <div className="inline-flex items-center justify-center w-full">
        <hr className="w-64 h-[2px] my-8 bg-gray-200 border-0 rounded-xl " />
        <div className="absolute px-4 -translate-x-1/2 bg-white left-1/2 ">
          <svg
            aria-hidden="true"
            className="w-5 h-5 text-gray-700 dark:text-gray-300"
            viewBox="0 0 24 27"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
              fill="currentColor"
            />
          </svg>
        </div>
      </div>
      <div className=" min-h-screen items-start justify-center grid md:grid-cols-2 lg:grid-cols-3   ">
        {datas &&
          datas.map &&
          datas.map((news: any) => (
            <div>
              <Card
                key={news.source.id}
                className=" sm:max-w-sm md:max-w-lg lg:max-w-2xl rounded overflow-hidden shadow-lg m-10"
                cover={
                  <img
                    className="relative h-1/4"
                    alt="example"
                    src={news.urlToImage}
                  />
                }
              >
                <p className=" text-xs absolute top-[15em] md:top-[15em] lg:top-[15.5em] left-0 px-2 py-1 rounded-br-md bg-red-800 text-white font-medium font-quicksand upercase">
                  Oleh : {news.author}
                </p>
                <p className="font-bold font-montserrat text-lg pb-3">
                  {news.title}
                </p>
                <p className=" font-light font-montserrat pb-5">
                  {news.description}
                </p>
                <div className="flex justify-between items-center font-light">
                  <p className="text-xs font-light font-montserrat">
                    {news.publishedAt}
                  </p>
                  <Button
                    type="text"
                    className=" text-red-700 font-semibold uppercase"
                  >
                    <Link href={news.url}>Read More</Link>
                  </Button>
                </div>
              </Card>
            </div>
          ))}
      </div>
      <footer className="sticky top-[100vh] text-center">
        <div className="mx-auto max-w-screen-xl px-10 pb-6 sm:w-full lg:w-full ">
          <div className="mx-auto max-w-5xl space-y-4  ">
            <span className="mt-4 block text-xs text-gray-500 dark:text-gray-400 dark:hover:text-white">
              &copy; Made with 🖤 by Tony
            </span>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Home;
